version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - bridge_net

  ts3:
    image: teamspeak
    container_name: ts3
    restart: always
    environment:
      TS3SERVER_LICENSE: accept
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - ts3_data:/var/ts3server
    networks:
      - bridge_net

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "3600" 
    networks:
      - bridge_net

volumes:
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
  ts3_data:
    driver: local

networks:
  bridge_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.1/16"
        - subnet: "2001:db8:1::/64"
